version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: deejay999/foodgram_project_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend/staticfiles/
      - media_value:/app/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: deejay999/foodgram_project_frontend:latest
    volumes:
      - result_build::/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
